# Generated by Django 4.0.3 on 2023-12-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='llm_output',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='llm_output',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
